### ISSUE TITLE
Build Failure: 'InterruptSpell' is not a member of 'PlayerbotAI' (Commit b949b50b)

### ISSUE THREAD

**Issue by jplrobinson-cyber** [mod-playerbots/mod-playerbots#2756]
Describe the bug:
Compiling the server fails due to a missing member function InterruptSpell in PlayerbotAI. This occurred immediately after updating the module to commit b949b50b. My main AzerothCore files on the Playerbot branch are fully up-to-date.

To Reproduce:

Pull the latest mod-playerbots commit: b949b50b (Merge pull request #2722).
Ensure the AzerothCore Playerbot branch is up-to-date.
Run CMake Configure and Generate.
Build worldserver in Visual Studio.
The build fails during the compilation of PlayerBotAIMethods.h.

Error Output:

Plaintext
Error C2039: 'InterruptSpell': is not a member of 'PlayerbotAI' - File: PlayerBotAIMethods.h - Line: 897
Error E0065: expected a ';' - File: MapDefines.h - Line: 86
Environment Setup:

OS: Windows
Core Version: AzerothCore (Playerbot branch)
Compiler: Visual Studio (RelWithDebInfo)
Bad Commit: b949b50bfcdd4fab937781bac2d7765e39330e4b (Merge PR #2722)
Last Working Commit: 2f7d9f77 (Rolling back to this commit allows the server to compile successfully)

**Comment by brighton-chi** [comment]
That's a mod-ale error, not Playerbots.

**Comment by Celandriel** [comment]
FYI mod-ale was just updated.

**Comment by jplrobinson-cyber** [comment]
I am very much a newbie here! How could I tell it is was an ALE error? I don't want to mistakenly raise an issue again!

**Comment by brighton-chi** [comment]
The file that is being referenced is not part of the Playerbots directory. But I think it's pretty understandable to see a file with that name and just assume it's Playerbots without questioning it.

**Comment by jplrobinson-cyber** [comment]
Thanks. I try better next time!
